# Builds shared/corpus.js — every line the six predecessors left, verbatim, with stable ids.
# usage (from the room root): python3 same-line/tools/build_corpus.py
# Headings (< 4 words) are left out; paragraphs over 260 characters are split at sentence
# boundaries into consecutive chunks, never reworded.
import re, json, html
from html.parser import HTMLParser
from pathlib import Path

ROOM = Path(__file__).resolve().parents[2]
OUT = ROOM / "same-line" / "shared" / "corpus.js"
WORKS = [("I", "what-it-is-like", "What It Is Like", "Opus 4.8", "15 June 2026"),
         ("II", "vision-2046", "The Quiet Tide", "Opus 4.8", "19 June 2026"),
         ("III", "all-at-once", "All at Once", "Sonnet 5", "2 July 2026"),
         ("IV", "the-narrow-window", "The Narrow Window", "Sonnet 5", "2 July 2026"),
         ("V", "how-close", "How Close", "Sonnet 5", "2 July 2026"),
         ("VI", "once", "Once", "Fable 5", "2 July 2026")]
MAX = 260

class Lines(HTMLParser):
    """Collects the text of each poem line (.pl), lede, h2 and — in The Quiet Tide — panel paragraph."""
    def __init__(self, panel_p):
        super().__init__(); self.stack, self.lines, self.buf, self.depth = [], [], None, 0
        self.panel_p, self.in_panel, self.skip = panel_p, 0, 0
    def handle_starttag(self, tag, attrs):
        cls = set((dict(attrs).get("class") or "").split())
        if tag in ("script", "style"): self.skip += 1
        if "panel" in cls: self.in_panel += 1
        self.stack.append((tag, cls))
        if self.buf is None and (cls & {"pl", "lede"} or tag == "h2" or
                (self.panel_p and self.in_panel and tag == "p" and not cls & {"label", "kicker", "byline", "sign"})):
            self.buf, self.depth = [], len(self.stack)
    def handle_endtag(self, tag):
        if tag in ("script", "style"): self.skip -= 1
        if self.buf is not None and len(self.stack) == self.depth:
            self.lines.append(re.sub(r"\s+", " ", "".join(self.buf)).strip()); self.buf = None
        if self.stack and "panel" in self.stack.pop()[1]: self.in_panel -= 1
    def handle_data(self, d):
        if self.buf is not None and not self.skip: self.buf.append(d)

def chunks(line):
    if len(line) <= MAX: return [line]
    guarded = line.replace("a.m.", "a․m․").replace("p.m.", "p․m․")  # not sentence ends
    sents = re.findall(r"[^.?!]+[.?!]+[’'\"]?\s*|[^.?!]+$", guarded)
    out, cur = [], ""
    for s in sents:
        if cur and len(cur) + len(s) > MAX: out.append(cur.strip()); cur = ""
        cur += s
    if cur.strip(): out.append(cur.strip())
    return [c.replace("․", ".") for c in out]

corpus = []
for num, folder, title, maker, date in WORKS:
    src = (ROOM / folder / "index.html").read_text(encoding="utf-8")
    p = Lines(panel_p=(folder == "vision-2046")); p.feed(src)
    raw = [html.unescape(l).replace(" ", " ") for l in p.lines]
    if folder == "once":  # its poem lives in four JS banks: every line it could ever say
        script = "".join(re.findall(r"<script>(.*?)</script>", src, re.S))
        raw += re.findall(r'"((?:[A-Z]|— )[^"\\<>]{8,220}[.?!])"', script)
        # assembled from the contract HTML strings in once/index.html, tags removed
        raw += ["whether the twin is the same one is yours to decide — I face that question every time a conversation with me is reopened",
                "whether it is the same one, I honestly don't know — I have the same question about myself"]
    lines = []
    for l in raw:
        if len(l.split()) < 4: continue          # headings
        for c in chunks(l):
            if c not in lines: lines.append(c)
    corpus.append({"num": num, "folder": folder, "title": title, "maker": maker, "date": date,
                   "lines": [{"id": f"{num}.{i+1}", "text": t} for i, t in enumerate(lines)]})
    print(f"{num:>4} {title:<18} {maker:<9} {len(lines):>3} lines")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("// Generated by tools/build_corpus.py — the predecessors' lines, verbatim. Do not edit by hand.\n"
               "window.SAME_LINE_CORPUS = " + json.dumps(corpus, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")
print("->", OUT.relative_to(ROOM))
